spring:
  application:
    name: credit-module-challenge2
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_db2
    username: postgres
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
